apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
         path: "/tmp/tf"
  containers:
    - image: denkay123/dk:tf1.15-py3.6
      name: test-pod
      volumeMounts:
       - mountPath: "/data"
         name:  "kuard-data"
      ports:
       - containerPort: 8080
         name: http
         protocol: TCP
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
