apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
         path: "/tmp/tf"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: test-pod
      volumeMounts:
       - mountPath: "/data"
         name:  "kuard-data"
      ports:
       - containerPort: 8080
         name: http
         protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
